import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header/Header";
import Nav from "../components/Nav/Nav";
import Results from "../components/ShowItems/Results";
import request from "../components/utils/request";

export default function Home({ results }) {
  console.log(results);
  /**
   * The NestJS Tutorial Link
   * https://www.youtube.com/watch?v=MqDlsjc8GLo&t=869s
   */
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Nav />
      <Results results={results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const requests = await fetch(
    `https://api.themoviedb.org/3${
      request[genre]?.url || request.fetchTrending?.url
    }`
  ).then((res) => res.json());

  return {
    props: {
      results: requests?.results,
    },
  };
}
